### PR TITLE
Added an useful Python script as example

### PR DESCRIPTION
**Pull request by malavolti**
I propose to add an example of Python script that could be useful to users who want to try your Qualys SSL Labs API implementation

### CODE REVIEW

**Comment by Shutgun** [comment]
Hi @malavolti , I like the idea of point out the main use case more explicitly. However, your way of using the API is more complicated that it has to be. I attached an alternative approach. If you like it, feel free to add it to your PR and we can add it to the readme.

```python
"""Get grade of multiple servers."""
import asyncio
import logging
from typing import List

from ssllabs import Ssllabs
from ssllabs.data.host import HostData


async def analyze() -> List[HostData]:
    """Analyze servers."""
    ssllabs = Ssllabs()
    if not await ssllabs.availability():
        raise

    servers = [
        "devolo.com",
        "www.devolo.com",
    ]

    return await asyncio.gather(
        *[ssllabs.analyze(host=host) for host in servers])


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(asctime)s: %(message)s")
    results = asyncio.run(analyze())
    for result in results:
        for endpoint in result.endpoints:
            if endpoint.grade:
                logging.info("Grade of %s (%s): %s", result.host, endpoint.ipAddress, endpoint.grade)
            else:
                logging.error(endpoint.statusMessage)
```

**Comment by malavolti** [comment]
Dear @Shutgun ,

I think that the solution you proposed doesn't do the same thing done by my solution.

On my example script I'm interacting with the SSLLabs API only if the last check has been done more than one hour before.

This help to reduce the interaction with the SSLLabs API and make script quicker.

In my script I've create a function that allow users to check a server by specify it as an argument and that function can be imported in a more complex program.

What do you think about this?

Thank you for the interest! 😊 🤗

**Comment by Shutgun** [comment]
Hi @malavolti ,

with version 1.2.0, your usecase should be covered by:

```python
"""Get grade of multiple servers."""
import asyncio
import logging
from typing import List

from ssllabs import Ssllabs
from ssllabs.data.host import HostData

HOSTS = [
    "devolo.com",
    "www.devolo.com",
]

async def analyze(hosts: List[str]) -> List[HostData]:
    """Analyze servers."""
    ssllabs = Ssllabs()
    if not await ssllabs.availability():
        raise
    return await asyncio.gather(*[ssllabs.analyze(host=host, from_cache=False, max_age=1) for host in hosts])

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(asctime)s: %(message)s")
    results = asyncio.run(analyze(HOSTS))
    for result in results:
        for endpoint in result.endpoints:
            if endpoint.grade:
                logging.info("Grade of %s (%s): %s", result.host, endpoint.ipAddress, endpoint.grade)
            else:
                logging.error(endpoint.statusMessage)
```

Do you want to extend the README accordingly? However, I guess for beginners I would leave out the parameters from_cache and max_age.

**Comment by malavolti** [comment]
Dear @Shutgun,

thank you so much for the new version and the new feature!

Please, add this part to your README as you wish and reject my Pull Request.

Best Regards,
Marco

**Pull request closed without merging**
