### PR TITLE
Add missing parameter for cached results

### PR DESCRIPTION
**Pull request by jrunu**
Setting startNew to off and maxAge will still trigger a new analysis. The parameter fromCache must be explicitly be set to on.

### CODE REVIEW

**Review by Shutgun — DISMISSED** [review]
LGTM :+1:

**Comment by 2Fake** [comment]
Closing because is hanging. Will reopen in a minute

**Comment by Shutgun** [comment]
Hi @jrunu , sorry for the noise but we had issues letting the CI run on your changes. Now it runs and has some suggestion about the formatting. Could you take care?

**Comment by jrunu** [comment]
Hi, no worries. I pushed a fix for the styling.

**Review by Shutgun — APPROVED** [review]

**Pull request merged**
