### PR TITLE
Added option to include endpoint details

### PR DESCRIPTION
**Pull request by alex-gts**
Allows for setting if full endpoint details are returned, and fixes a bug where endpoint details weren't returned when retrieving results from cache.

### CODE REVIEW

**Comment by Shutgun** [comment]
Hi @alex-gts , the more I think about it, I guess it was not intended to hide the endpoint details. Am I right that by adding

`            all="done",`

as line 77 the issue is fixed? By reading the API docs and doing some tests I didn't find any reason to use off on the high level. And if it really is that easy, I guess I would also strip the include_details parameter.

**Comment by alex-gts** [comment]
Hi @Shutgun,

The only reason I added it in is that not requesting full details could be quicker. Therefore, if someone was optimising for speed they could omit the slower, more detailed report.

This is why I added the extra check at line 86, so that you can choose to not return details, extending the existing functionality that returned full details regardless.

It is fully backward compatible, and so having the extra parameter poses no risk to existing implementations.

That said, it does not directly affect my use case and so my issue would be fixed by just `all="done"` as you mentioned.

**Comment by Shutgun** [comment]
I made a few (to be honest not many) tests on the performance and I don't think it makes any difference. To keep the code simple: could you change the PR to just adding the all parameter?

**Comment by Shutgun** [comment]
The test failure in unrelated and comes from a change in behavior of pytest-httpx. Don't worry about that.

**Comment by alex-gts** [comment]
All done, I've removed the `include_details` parameter.

The only change now is the addition of `all="done"` at line 77.

**Review by Shutgun — APPROVED** [review]

**Comment by Shutgun** [comment]
Hi @alex-gts , the workflow does not allow me to merge your code with a broken CI. So we need to do two more things, please:

1. I fixed pytest-httpx errors in https://github.com/devolo/ssllabs/pull/63, so you'd need to rebase your branch.
2. In order to respect your change and make the tests green, you need to change two lines in tests/test_ssllabs.py.

Line 47 gets to: 
`host="devolo.de", ignoreMismatch="off", publish="off", startNew="on", fromCache="off", maxAge=None, all="done"`
Line 52 gets to:
`host="devolo.de", ignoreMismatch="off", publish="off", startNew="off", fromCache="on", maxAge=1, all="done"`

**Review by Shutgun — APPROVED** [review]

**Pull request merged**
